<?php

class DataPrivacyTableSeeder extends Seeder {

	public function run()
	{
		// Uncomment the below to wipe the table clean before populating
		DB::table('data_privacy')->truncate();

		$data_privacy = array(
			array(
				'data_id'=>1,
				'agency_id'=>1,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>1,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>1,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>2,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>2,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>2,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>3,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>3,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>3,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>4,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>4,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>4,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>5,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>5,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>5,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>6,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>6,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>6,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>7,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>7,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>7,
				'status'=>false
				),			

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>9,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>9,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>9,
				'status'=>false
				),			

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>10,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>10,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>10,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>11,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>11,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>11,
				'status'=>false
				),

//----------------------------------------------------//
			array(
				'data_id'=>1,
				'agency_id'=>12,
				'status'=>true
				),
			array(
				'data_id'=>2,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>3,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>4,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>5,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>6,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>7,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>8,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>9,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>10,
				'agency_id'=>12,
				'status'=>false
				),
			array(
				'data_id'=>11,
				'agency_id'=>12,
				'status'=>false
				),			
		);

		// Uncomment the below to run the seeder
		DB::table('data_privacy')->insert($data_privacy);
	}

}
